CREATE TABLE [dbo].AchBatch
(
    [Id]                        UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [RecordType]                TINYINT          NOT NULL DEFAULT 5,
    [ServiceClassCode]          SMALLINT         NOT NULL,
    [Name]                      NVARCHAR(16)     NOT NULL,
    [DiscretionaryData]         NVARCHAR(20)     NOT NULL,
    [Identification]            NVARCHAR(10)     NOT NULL,
    [EntryClassCode]            NCHAR(3)         NOT NULL,
    [EntryDescription]          NVARCHAR(10)     NOT NULL,
    [DescriptiveDate]           NVARCHAR(6)      NOT NULL,
    [EffectiveEntryDate]        DATETIME2        NOT NULL,
    [SettlementDateJulian]      SMALLINT         NOT NULL,
    [OriginatorStatusCode]      NCHAR(1)         NOT NULL,
    [OriginatingDfiId]          NCHAR(8)         NOT NULL,
    [BatchNumber]               INT              NOT NULL,
    [ControlRecordType]         TINYINT          NOT NULL DEFAULT 8,
    [ControlServiceClassCode]   SMALLINT         NOT NULL,
    [EntryAndAddendaCount]      INT              NOT NULL,
    [EntryHash]                 BIGINT           NOT NULL,
    [TotalDebitAmount]          DECIMAL(20, 2)   NOT NULL,
    [TotalCreditAmount]         DECIMAL(20, 2)   NOT NULL,
    [ControlIdentification]     NVARCHAR(10)     NOT NULL,
    [MessageAuthenticationCode] NVARCHAR(19)     NOT NULL,
    [Reserved]                  NVARCHAR(6)      NOT NULL,
    [ControlOriginatingDfiId]   NCHAR(8)         NOT NULL,
    [ControlBatchNumber]        INT              NOT NULL, 
    [AchFileId]                 UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [FK_AchBatch_ToAchFile] FOREIGN KEY ([AchFileId]) REFERENCES [dbo].[AchFile]([Id]) ON DELETE CASCADE
)
