CREATE TABLE [dbo].[AchReasonCode]
(
	[Id] NCHAR(3) NOT NULL PRIMARY KEY,
	[Title] NVARCHAR(128) NOT NULL,
	[Description] NVARCHAR(1024) NULL,
	[DateCreated] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[CreatedBy] SYSNAME NOT NULL DEFAULT SUSER_NAME(),
	[UpdatedBy] SYSNAME NOT NULL DEFAULT SUSER_NAME()
)
